const canvas = document.querySelector('#game-canvas');
const ctx = canvas.getContext('2d');
const overlay = document.querySelector('#overlay');
const overlayTitle = document.querySelector('#overlay-title');
const overlayCopy = document.querySelector('#overlay-copy');
const scoreEl = document.querySelector('#score');
const comboEl = document.querySelector('#combo');
const livesEl = document.querySelector('#lives');
let player; let drops; let particles; let keys = {}; let score = 0; let combo = 0; let lives = 3; let shield = 0; let running = false; let spawnTimer = 0; let lastTime = 0; let animation;

function resize() { const ratio = Math.min(window.devicePixelRatio || 1, 2); const rect = canvas.getBoundingClientRect(); canvas.width = rect.width * ratio; canvas.height = rect.height * ratio; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); }
function width() { return canvas.clientWidth; }
function height() { return canvas.clientHeight; }
function reset() { resize(); player = { x: width() / 2, y: height() - 34, width: 82, speed: 390 }; drops = []; particles = []; score = 0; combo = 0; lives = 3; shield = 0; spawnTimer = .2; updateHud(); }
function updateHud() { scoreEl.textContent = String(score).padStart(6, '0'); comboEl.textContent = `x${Math.max(1, combo)}`; livesEl.textContent = `${'♥ '.repeat(lives)}${'♡ '.repeat(3 - lives)}`.trim(); }
function start() { reset(); running = true; overlay.classList.add('hidden'); lastTime = performance.now(); animation = requestAnimationFrame(loop); }
function end() { running = false; cancelAnimationFrame(animation); overlayTitle.textContent = `RUN OVER / ${score.toLocaleString()}`; overlayCopy.textContent = `You built a x${Math.max(1, combo)} combo. The sky wins this round, but your next catch can beat the score.`; document.querySelector('#start').textContent = 'PLAY AGAIN'; overlay.classList.remove('hidden'); }
function spawn() { const roll = Math.random(); const type = roll < .14 ? 'bomb' : roll < .23 ? 'gold' : roll < .27 ? 'shield' : 'balloon'; const radius = type === 'bomb' ? 15 : 13 + Math.random() * 4; drops.push({ type, x: radius + Math.random() * (width() - radius * 2), y: -radius * 2, radius, speed: 78 + Math.random() * 44 + Math.min(combo * 2, 80), sway: (Math.random() - .5) * 28, phase: Math.random() * 6.28 }); }
function burst(x, y, color) { for (let i = 0; i < 12; i += 1) particles.push({ x, y, vx: (Math.random() - .5) * 150, vy: (Math.random() - .5) * 150, life: .55, color }); }
function loseLife() { if (shield > 0) { shield = 0; burst(player.x, player.y, '#00e5ff'); return; } lives -= 1; combo = 0; burst(player.x, player.y, '#ff2f78'); if (lives <= 0) end(); }
function catchDrop(drop) { const caught = drop.y + drop.radius > player.y - 12 && drop.y - drop.radius < player.y + 10 && Math.abs(drop.x - player.x) < player.width / 2 + drop.radius; if (!caught) return false; if (drop.type === 'bomb') loseLife(); else if (drop.type === 'gold') { combo += 1; score += 300 * Math.max(1, combo); burst(drop.x, drop.y, '#ffe16b'); } else if (drop.type === 'shield') { shield = 1; combo += 1; score += 150 * Math.max(1, combo); burst(drop.x, drop.y, '#00e5ff'); } else { combo += 1; score += 100 * Math.max(1, combo); burst(drop.x, drop.y, '#ff2f78'); } updateHud(); return true; }
function update(dt) { const direction = (keys.ArrowRight || keys.d ? 1 : 0) - (keys.ArrowLeft || keys.a ? 1 : 0); player.x = Math.max(player.width / 2, Math.min(width() - player.width / 2, player.x + direction * player.speed * dt)); spawnTimer -= dt; if (spawnTimer <= 0) { spawn(); spawnTimer = Math.max(.22, .7 - Math.min(combo * .012, .28)); } drops.forEach((drop) => { drop.y += drop.speed * dt; drop.x += Math.sin(drop.y / 40 + drop.phase) * drop.sway * dt; }); drops = drops.filter((drop) => { if (catchDrop(drop)) return false; if (drop.y - drop.radius > height()) { if (drop.type !== 'bomb') combo = 0; return false; } return true; }); particles.forEach((particle) => { particle.x += particle.vx * dt; particle.y += particle.vy * dt; particle.life -= dt; }); particles = particles.filter((particle) => particle.life > 0); updateHud(); }
function drawBalloon(drop) { const color = drop.type === 'bomb' ? '#272632' : drop.type === 'gold' ? '#ffe16b' : drop.type === 'shield' ? '#00e5ff' : '#ff2f78'; ctx.save(); ctx.translate(drop.x, drop.y); ctx.fillStyle = color; ctx.shadowBlur = 16; ctx.shadowColor = color; ctx.beginPath(); ctx.ellipse(0, 0, drop.radius * .8, drop.radius, 0, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; ctx.strokeStyle = color; ctx.beginPath(); ctx.moveTo(0, drop.radius); ctx.lineTo(0, drop.radius + 12); ctx.stroke(); if (drop.type === 'bomb') { ctx.fillStyle = '#ff5b78'; ctx.font = 'bold 14px Space Mono'; ctx.textAlign = 'center'; ctx.fillText('!', 0, 5); } else if (drop.type === 'gold') { ctx.fillStyle = '#5b4210'; ctx.font = 'bold 11px Space Mono'; ctx.textAlign = 'center'; ctx.fillText('+', 0, 4); } else if (drop.type === 'shield') { ctx.strokeStyle = '#fff'; ctx.beginPath(); ctx.arc(0, 0, 6, 0, Math.PI * 2); ctx.stroke(); } ctx.restore(); }
function draw() { ctx.clearRect(0, 0, width(), height()); ctx.strokeStyle = 'rgba(255,255,255,.06)'; for (let x = 0; x < width(); x += 44) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, height()); ctx.stroke(); } for (let y = 0; y < height(); y += 44) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(width(), y); ctx.stroke(); } drops.forEach(drawBalloon); ctx.fillStyle = shield ? '#00e5ff' : '#fff'; ctx.shadowBlur = shield ? 20 : 10; ctx.shadowColor = shield ? '#00e5ff' : '#fff'; ctx.fillRect(player.x - player.width / 2, player.y, player.width, 12); ctx.fillStyle = '#ff2f78'; ctx.fillRect(player.x - 16, player.y - 8, 32, 8); ctx.shadowBlur = 0; particles.forEach((particle) => { ctx.globalAlpha = Math.max(0, particle.life * 2); ctx.fillStyle = particle.color; ctx.fillRect(particle.x, particle.y, 3, 3); }); ctx.globalAlpha = 1; }
function loop(time) { if (!running) return; const dt = Math.min((time - lastTime) / 1000, .04); lastTime = time; update(dt); draw(); animation = requestAnimationFrame(loop); }
document.addEventListener('keydown', (event) => { keys[event.key] = true; if (['ArrowLeft', 'ArrowRight'].includes(event.key)) event.preventDefault(); }); document.addEventListener('keyup', (event) => { keys[event.key] = false; }); window.addEventListener('resize', resize); document.querySelector('#start').addEventListener('click', start); document.querySelectorAll('.mobile-controls button').forEach((button) => { const key = button.dataset.key; button.addEventListener('pointerdown', () => { keys[key] = true; }); button.addEventListener('pointerup', () => { keys[key] = false; }); button.addEventListener('pointerleave', () => { keys[key] = false; }); }); reset();
