const canvas = document.querySelector('#game-canvas');
const ctx = canvas.getContext('2d');
const overlay = document.querySelector('#overlay');
const overlayTitle = document.querySelector('#overlay-title');
const overlayCopy = document.querySelector('#overlay-copy');
const scoreEl = document.querySelector('#score');
const waveEl = document.querySelector('#wave');
const livesEl = document.querySelector('#lives');
let player; let enemies; let shots; let particles; let keys = {}; let score = 0; let wave = 1; let lives = 3; let running = false; let lastTime = 0; let spawnTimer = 0; let animation;

function resize() { const ratio = Math.min(window.devicePixelRatio || 1, 2); const rect = canvas.getBoundingClientRect(); canvas.width = rect.width * ratio; canvas.height = rect.height * ratio; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); }
function width() { return canvas.clientWidth; } function height() { return canvas.clientHeight; }
function reset() { resize(); player = { x: width() / 2, y: height() - 48, speed: 360, cooldown: 0, invincible: 0 }; enemies = []; shots = []; particles = []; score = 0; wave = 1; lives = 3; spawnTimer = 0; updateHud(); }
function updateHud() { scoreEl.textContent = String(score).padStart(6, '0'); waveEl.textContent = String(wave).padStart(2, '0'); livesEl.textContent = `${'♥ '.repeat(lives)}${'♡ '.repeat(3 - lives)}`.trim(); }
function start() { reset(); running = true; overlay.classList.add('hidden'); lastTime = performance.now(); animation = requestAnimationFrame(loop); }
function end() { running = false; cancelAnimationFrame(animation); overlayTitle.textContent = `RUN OVER / ${score.toLocaleString()}`; overlayCopy.textContent = `You reached wave ${wave}. The swarm won this time, but your high score is still alive.`; document.querySelector('#start').textContent = 'PLAY AGAIN'; overlay.classList.remove('hidden'); }
function spawnEnemy() { const size = 12 + Math.random() * 8; enemies.push({ x: size + Math.random() * (width() - size * 2), y: -size, size, speed: 42 + wave * 8 + Math.random() * 34, drift: (Math.random() - .5) * 30, hp: wave > 4 && Math.random() < .15 ? 2 : 1 }); }
function fire() { if (player.cooldown > 0) return; shots.push({ x: player.x, y: player.y - 16, speed: 560 }); player.cooldown = .2; }
function burst(x, y, color) { for (let i = 0; i < 9; i += 1) particles.push({ x, y, vx: (Math.random() - .5) * 150, vy: (Math.random() - .5) * 150, life: .5, color }); }
function update(dt) { const direction = (keys.ArrowRight || keys.d ? 1 : 0) - (keys.ArrowLeft || keys.a ? 1 : 0); player.x = Math.max(18, Math.min(width() - 18, player.x + direction * player.speed * dt)); if (keys.w || keys.W || keys[' '] || keys.Space) fire(); player.cooldown = Math.max(0, player.cooldown - dt); player.invincible = Math.max(0, player.invincible - dt); spawnTimer -= dt; if (spawnTimer <= 0) { spawnEnemy(); spawnTimer = Math.max(.25, .9 - wave * .06); }
  shots.forEach((shot) => { shot.y -= shot.speed * dt; }); shots = shots.filter((shot) => shot.y > -20);
  enemies.forEach((enemy) => { enemy.y += enemy.speed * dt; enemy.x += Math.sin(enemy.y / 28) * enemy.drift * dt; });
  for (const enemy of enemies) { if (enemy.y > height() + 24) { enemy.dead = true; loseLife(); } if (player.invincible <= 0 && Math.hypot(enemy.x - player.x, enemy.y - player.y) < enemy.size + 15) { enemy.dead = true; loseLife(); } for (const shot of shots) if (!shot.dead && !enemy.dead && Math.hypot(enemy.x - shot.x, enemy.y - shot.y) < enemy.size + 5) { shot.dead = true; enemy.hp -= 1; if (enemy.hp <= 0) { enemy.dead = true; score += 100 * wave; burst(enemy.x, enemy.y, '#ff2f78'); } } }
  enemies = enemies.filter((enemy) => !enemy.dead); shots = shots.filter((shot) => !shot.dead); const nextWave = Math.floor(score / 1200) + 1; if (nextWave > wave) { wave = nextWave; updateHud(); } particles.forEach((particle) => { particle.x += particle.vx * dt; particle.y += particle.vy * dt; particle.life -= dt; }); particles = particles.filter((particle) => particle.life > 0); updateHud(); }
function loseLife() { if (player.invincible > 0) return; lives -= 1; player.invincible = 1.2; burst(player.x, player.y, '#00e5ff'); if (lives <= 0) end(); }
function draw() { ctx.clearRect(0, 0, width(), height()); ctx.strokeStyle = 'rgba(0,229,255,.08)'; ctx.lineWidth = 1; for (let x = 0; x < width(); x += 40) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, height()); ctx.stroke(); } for (let y = 0; y < height(); y += 40) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(width(), y); ctx.stroke(); } if (player.invincible % .2 < .1) { ctx.fillStyle = '#00e5ff'; ctx.shadowBlur = 20; ctx.shadowColor = '#00e5ff'; ctx.beginPath(); ctx.moveTo(player.x, player.y - 18); ctx.lineTo(player.x - 15, player.y + 14); ctx.lineTo(player.x, player.y + 8); ctx.lineTo(player.x + 15, player.y + 14); ctx.closePath(); ctx.fill(); ctx.shadowBlur = 0; } shots.forEach((shot) => { ctx.fillStyle = '#ffe16b'; ctx.fillRect(shot.x - 2, shot.y - 9, 4, 14); }); enemies.forEach((enemy) => { ctx.fillStyle = enemy.hp > 1 ? '#ffe16b' : '#ff2f78'; ctx.shadowBlur = 14; ctx.shadowColor = ctx.fillStyle; ctx.beginPath(); ctx.moveTo(enemy.x, enemy.y - enemy.size); ctx.lineTo(enemy.x + enemy.size, enemy.y); ctx.lineTo(enemy.x, enemy.y + enemy.size); ctx.lineTo(enemy.x - enemy.size, enemy.y); ctx.closePath(); ctx.fill(); ctx.shadowBlur = 0; }); particles.forEach((particle) => { ctx.globalAlpha = Math.max(0, particle.life * 2); ctx.fillStyle = particle.color; ctx.fillRect(particle.x, particle.y, 3, 3); }); ctx.globalAlpha = 1; }
function loop(time) { if (!running) return; const dt = Math.min((time - lastTime) / 1000, .04); lastTime = time; update(dt); draw(); animation = requestAnimationFrame(loop); }
document.addEventListener('keydown', (event) => { keys[event.key] = true; if (['ArrowLeft', 'ArrowRight', ' ', 'w', 'W'].includes(event.key)) event.preventDefault(); }); document.addEventListener('keyup', (event) => { keys[event.key] = false; }); window.addEventListener('resize', resize); document.querySelector('#start').addEventListener('click', start); document.querySelectorAll('.mobile-controls button').forEach((button) => { const key = button.dataset.key; button.addEventListener('pointerdown', () => { keys[key] = true; }); button.addEventListener('pointerup', () => { keys[key] = false; }); button.addEventListener('pointerleave', () => { keys[key] = false; }); }); reset();
